function regions_map = getAllenRegionMap(version)

    if(nargin < 1), version = 2; end % latest

    switch version
        case 2
            % see allenmap_numbering.PNG. -r for right hemesphere, -l for left, -b
            % for bilateral. Names follow https://connectivity.brain-map.org/3d-viewer
            regions_map = containers.Map(...
                ["MO-r", "SS-r", "AUD-r", "VIS-r", "ACA-r", "RSP-r", "PTL-p-r",  ...
                 "MOp-r", "MOs-r", ...
                 "M1-r", "M2-r",...
                 "SSp-r", "SSs-r", ...
                 "SSp-n-r", "SSp-bfd-r", "SSp-ll-r", "SSP-m-r", "SSp-ul-r", "SSP-tl-r", "SSP-un-r", ...
                 "VISal-r", "VISam-r", "VISI-r", "VISp-r", "VISpl-r", "VISpm-r", "VISli-r", "Vispor-r", ...
                 "RSP-alg-r", "RSPd-r", "RSPv-r", ...
                 "V1-r", ...
                 "V1-l", "RSP-l", ...
                 "RSP-b", "RSPd-b", ...
                 "DEC"... % cerebellum CB-CBX-VERM-DEC
                 ],...
                {[4,6], 8:2:22, 24:2:30, 32:2:46, 60, [50,64,66], [54,56],...
                 4, 6, ...
                 4, 6,...
                 8:20, 22, ...
                 8, 10, 12, 14, 16, 18, 20, ...
                 32, 34, 36, 38, 40, 42, 44, 46, ...
                 50, 64, 66, ...
                 38, ...
                 37, [49,65,67], ...
                 49:52, 51, ...
                 72});

        case 1
            regions_map = containers.Map(...
                ["M1", "SSp-bfd", "SSp-ll", "V1", "RSP"], ...
                [4,10, 12,38,51]);

        otherwise
            regions_map = [];
            error("getAllenRegionMap: unknown version %d", version);
    end
       
end