function [Mdownsampled] = DownsampleSpace(Mraw,nsaverage)

    sizen = max(floor(size(Mraw, 1)/ nsaverage), 1);
    sizem = max(floor(size(Mraw, 2)/ nsaverage), 1);
    sizet = size(Mraw, 3);
    
    if(nsaverage == 1)
        Mdownsampled = Mraw;
        return;
    end

    Mdownsampled = ...
        squeeze(mean(...
            reshape(...
                permute(...
                    reshape(Mraw(1:sizen*nsaverage, 1:sizem*nsaverage, :), ...
                            nsaverage,sizen,nsaverage,sizem,[]), ...
                        [1,3,2,4,5]), ...
                nsaverage, nsaverage, sizen, sizem, []), ...
            [1,2]));
end

