% basepath = "\\VoltageRaw\DCIMG\GEVI_Wave\Raw\Anesthesia\m973\20191002\meas07\";
% binning = 8;
% maxRAM = 0.05;
% unaccounted_hardware_binning = 1; %For old recordings, hardware binning is not accounted for.
 

basefilename = dir(fullfile(basepath, '*G.dcimg')).name(1:(end-7));
channels = ["G", "R"];
extention = ".dcimg";

filepath_parts = strsplit(basepath,{'/','\'});
filepath_parts = filepath_parts(~(filepath_parts == "" | filepath_parts == "DCIMG"));

% out_folder = "F:\GEVI_Wave\Preprocessed\Anesthesia\m45\20211007\meas01_paperplots";
out_folder = strjoin([{'F:'}, filepath_parts(2), {'Preprocessed'},...
                      filepath_parts(4:(length(filepath_parts)))], '/')
%%

time_start = tic;
[h5path1,summary1] = ...
    convertRaw2Preproc1(char(fullfile(basepath, basefilename + channels(1) + extention)), ...
                        'binning', binning, 'useMovieSpecs', 1, ...
                        'expPath', char(out_folder),...
                        'maxRAM', maxRAM, 'parallel', false, ...
                        'useDCIMGmex', true, 'skip', true, ...
                        'hardware_binning', unaccounted_hardware_binning, ...
                        'binning_postfix', true, 'binning_postfix', true);
h5path1 = movieAddTimestampsTable(h5path1);
%%
[h5path2,summary2] = ...
    convertRaw2Preproc1(char(fullfile(basepath, basefilename + channels(2) + extention)), ...
                        'binning', binning, 'useMovieSpecs', 1, ...
                        'expPath', char(out_folder),...
                        'maxRAM', maxRAM, 'parallel', false,...
                        'useDCIMGmex', true, 'skip', true, ...
                        'hardware_binning', unaccounted_hardware_binning, ...
                        'binning_postfix', true);

time_taken  = toc(time_start);
h5path2 = movieAddTimestampsTable(h5path2);
%%

movieMeanTraces([string(h5path1), string(h5path2)]);