function movie_specs = h5readMovieSpecs(h5filename)
%h5readMovie reads specs (MovieSpecs class object) from .h5 movie file
    
    movie_specs = MovieSpecs( cell2mat(h5read(h5filename, '/history')), ...
                                       h5read(h5filename, '/fps'),...
                                       h5read(h5filename, '/pixsize'),... 
                                       h5read(h5filename, '/binning'),... 
                                       h5read(h5filename, '/spaceorigin'),... 
                                       h5read(h5filename, '/timebinning'),... 
                                       h5read(h5filename, '/timeorigin'),... 
                              cell2mat(h5read(h5filename, '/sourcePath')));
                                   
end

